# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('patronyc', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=0)),
                ('is_deleted', models.BooleanField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(upload_to='films_polls/%Y/%m/%d'),
        ),
    ]
