# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_polls', '0004_auto_20170311_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=0),
        ),
    ]
