# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films_polls', '0005_auto_20170311_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_id', models.IntegerField()),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films_polls.Film')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films_polls.User')),
            ],
        ),
    ]
