# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_polls', '0007_auto_20170311_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 13, 41, 24, 783630)),
        ),
    ]
