# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films_polls', '0008_auto_20170312_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='mark_id',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='film',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 16, 4, 26, 376563)),
        ),
        migrations.AddField(
            model_name='comment',
            name='film_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films_polls.Film'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films_polls.CustomUser'),
        ),
    ]
