# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_polls', '0010_auto_20170312_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 16, 16, 17, 385074)),
        ),
    ]
