# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_polls', '0012_auto_20170312_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 16, 23, 57, 635783)),
        ),
        migrations.AlterField(
            model_name='film',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 16, 23, 57, 633312)),
        ),
    ]
