# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_polls', '0013_auto_20170312_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 16, 26, 9, 176644)),
        ),
        migrations.AlterField(
            model_name='film',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 16, 26, 9, 174112)),
        ),
    ]
