# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_polls', '0014_auto_20170312_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 13, 16, 44, 7, 918678)),
        ),
        migrations.AlterField(
            model_name='film',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 13, 16, 44, 7, 916128)),
        ),
    ]
